---
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - vendor/bundle/**/*
    - node_modules/**/*
    - Procfile

require:
  - "test_prof/rubocop"
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  # Commonly used screens these days easily fit more than 80 characters.
  Max: 120
  Exclude:
    - "spec/**/*.rb"

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "lib/devengo/container/**/*.rb"
    - "lib/devengo/container/container.rb"
    - "**/*.rake"
    - "spec/**/*.rb"

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/ClassEqualityComparison:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/NumericPredicate:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

# (new in 1.1)
Style/ArgumentsForwarding:
  Enabled: true

# (new in 1.1)
Style/DocumentDynamicEvalDefinition:
  Enabled: true

# (new in 1.1)
Style/SwapValues:
  Enabled: true

# (new in 1.2)
Style/CollectionCompact:
  Enabled: true

# (new in 1.2)
Style/NegatedIfElseCondition:
  Enabled: true

# (new in 1.3)
Style/NilLambda:
  Enabled: true

# (new in 1.4)
Style/RedundantArgument:
  Enabled: true

Style/FetchEnvVar:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/HashCompareByIdentity:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

# (new in 1.1)
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

# (new in 1.1)
Lint/EmptyBlock:
  Enabled: true

# (new in 1.1)
Lint/ToEnumArguments:
  Enabled: true

# (new in 1.1)
Lint/UnmodifiedReduceAccumulator:
  Enabled: true

# (new in 1.2)
Lint/NoReturnInBeginEndBlocks:
  Enabled: true

# (new in 1.3)
Lint/DuplicateBranch:
  Enabled: true

# (new in 1.3)
Lint/EmptyClass:
  Enabled: true

# (new in 1.5)
Lint/UnexpectedBlockArity:
  Enabled: true

RSpec/AggregateExamples:
  AddAggregateFailuresMetadata: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/BeNil:
  Enabled: false

RSpec/BeEq:
  Enabled: false
