---
name: release

# https://github.com/adrienverge/yamllint/issues/430
"on":
  push:
    tags:
      - v*.*.*
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@master # yamllint disable-line
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          RELEASE_COMMAND: rake release
